import jittor as jt

#The SterchMap is generated by WorldCoord_Map   

def computeStretchMap(WorldCoord_Map,padding_method='replicate'):
    WorldCoord_Map=jt.array(WorldCoord_Map.copy()).float32()
    if padding_method == 'replicate':
        WorldCoord_Map_x = jt.concat([WorldCoord_Map,WorldCoord_Map[:,-1:,:]],dim=1)
        WorldCoord_Map_y = jt.concat([WorldCoord_Map,WorldCoord_Map[-1:,:,:]],dim=0)
        
    stretchU=1/jt.sum((WorldCoord_Map[:,:,:]-WorldCoord_Map_x[:,1:,:]).pow(2),dim=2).sqrt()
    stretchV=1/jt.sum((WorldCoord_Map[:,:,:]-WorldCoord_Map_y[1:,:,:]).pow(2),dim=2).sqrt()
    return stretchU,stretchV
